name: "python virtualenv PPA CI workflow ubuntu"


on:
  push:
    branches: [ test ]



jobs:

  ubuntu-2004-python3x-PPA-job:
    name: "Setting Up Python 3x PPA on ubuntu-20.04"
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status  
    - name: "Setting Up Python 3x virtual environment (.virtualenv)"
      run: |
        set -o errexit
        set -o pipefail
        set -o nounset
        set -o xtrace
        echo "=============Setting Up Python 3x Virtual Environment=="
        sudo apt-get update -qq
        python --version
        python2 -V
        python3 -V
        sudo pip3 install virtualenv
        virtualenv .virtualenv
        . .virtualenv/bin/activate
        python --version
        python -V
        python3 -V
        python2 -V        
        pip install -r requirements.txt
        echo "=============Add Deadsnakes PPA============="
        sudo add-apt-repository ppa:deadsnakes/ppa
        sudo apt-get update -qq
        sudo apt-get install python3.8 -qqy
        python ––version
        python -V
        python3 -V
        python2 -V   
        echo "=============Add Deadsnakes PPA============="   
        deactivate
        python --version
        python -V
        python3 -V
        python2 -V 
