name: "python virtualenv pip pip3 VIRTUALENVWRAPPER CI workflow ubuntu latest"


on:
  push:
    branches: [ test ]



jobs:

  ubuntu-2004-python3x-virtualenv-pip:
    name: "Setting Up Python 3x virtualenv on ubuntu-latest"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status 
    - name: "Setting Up Python 3x virtual environment (Pipenv)"
      run: |
        set -o errexit
        set -o pipefail
        set -o nounset
        set -o xtrace
        echo "=============Setting Up Virtualenv============="
        sudo apt-get update -qq
        whoami
        pwd && ls -lai
        python --version
        python -V
        python3 -V
        python2 -V
        #Installing virtualenv
        pip --version
        pip install virtualenv
        virtualenv --version
        virtualenv venv
        source venv/bin/activate
        pip install requests
        #create a requirements.txt file, which contains a simple list of all the packages in the current environment, and their respective versions
        pip freeze > requirements.txt
        #list of installed packages without the requirements
        pip list
        deactivate        
        python --version
        python -V
        python3 -V
        python2 -V   

  ubuntu-2004-python3x-virtualenv-pip-python2x:
    name: "Setting Up Python 3x virtualenv on ubuntu-latest"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status 
    - name: "Setting Up Python 3x virtual environment (Pipenv) python2x"
      run: |
        set -o errexit
        set -o pipefail
        set -o nounset
        set -o xtrace
        echo "=============Setting Up Virtualenv============="
        sudo apt-get update -qq
        whoami
        pwd && ls -lai
        python --version
        python -V
        python3 -V
        python2 -V
        #Installing virtualenv
        pip --version
        pip install virtualenv
        virtualenv --version
        #use the Python interpreter of your choice (like python2.7)
        virtualenv -p /usr/bin/python2.7 venv        
        source venv/bin/activate
        pip install requests
        #create a requirements.txt file, which contains a simple list of all the packages in the current environment, and their respective versions
        pip freeze > requirements.txt
        #list of installed packages without the requirements
        pip list
        deactivate        
        python --version
        python -V
        python3 -V
        python2 -V   


  ubuntu-2004-python3x-virtualenv-pip-VIRTUALENVWRAPPER-python2x:
    name: "Setting Up Python 3x virtualenv (Pipenv) on ubuntu-latest"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status 
    - name: "Setting Up Python 3x virtual environment (Pipenv) VIRTUALENVWRAPPER python2x"
      run: |
        set -o errexit
        set -o pipefail
        set -o nounset
        set -o xtrace
        echo "=============Setting Up Virtualenv============="
        sudo apt-get update -qq
        whoami
        pwd && ls -lai
        python --version
        python -V
        python3 -V
        python2 -V
        #Installing virtualenv
        pip --version
        pip install virtualenv
        virtualenv --version
        #change the interpreter globally with an env variable in ~/.bashrc
        export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python2.7       
        source venv/bin/activate
        pip install requests
        #create a requirements.txt file, which contains a simple list of all the packages in the current environment, and their respective versions
        pip freeze > requirements.txt
        #list of installed packages without the requirements
        pip list
        deactivate        
        python --version
        python -V
        python3 -V
        python2 -V 


  ubuntu-2004-python3x-python3venv-job:
    name: "Setting Up Python 3x (python3-venv) on ubuntu-latest"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status 
    - name: "Setting Up Python 3x virtual environment (python3-venv)"
      run: |
        set -o errexit
        set -o pipefail
        set -o nounset
        set -o xtrace
        echo "=============Setting Up a Python 3x Virtual Environment=="
        sudo apt-get update -qq
        whoami
        pwd && ls -lai
        python --version
        python -V
        python3 -V
        python2 -V
        sudo apt-get install -qqy python3-venv
        python3 -m venv my_env
        ls my_env
        source my_env/bin/activate
        python --version
        python -V
        python3 -V
        python2 -V
        pip install -r requirements.txt
        deactivate
        python --version
        python -V
        python3 -V
        python2 -V   

  ubuntu-2004-python3x-pip3-source-virtualenv-job:
    name: "Setting Up Python 3x (source virtualenv) on ubuntu-latest"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status             
    - name: "Setting Up Python 3x virtual environment (source virtualenv)"
      run: |
        set -o errexit
        set -o pipefail
        set -o nounset
        set -o xtrace
        echo "=============Setting Up Python 3x Virtual Environment=="        
        sudo apt-get update -qq
        python --version
        python -V
        python3 -V
        python2 -V
        sudo pip3 install virtualenv
        virtualenv -p $(which python3) ~venvpy3
        source ~venvpy3/bin/activate
        python --version
        python2 -V
        python3 -V
        pip install -r requirements.txt
        deactivate
        python --version
        python -V
        python3 -V
        python2 -V   

  ubuntu-2004-python3x-pip3-virtualenv-job:
    name: "Setting Up Python 3x (.virtualenv) on ubuntu-latest"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status  
    - name: "Setting Up Python 3x pip3 (.virtualenv)"
      run: |
        set -o errexit
        set -o pipefail
        set -o nounset
        set -o xtrace
        echo "=============Setting Up Python 3x Virtual Environment=="
        sudo apt-get update -qq
        python --version
        python2 -V
        python3 -V
        sudo pip3 install virtualenv
        virtualenv .virtualenv
        . .virtualenv/bin/activate
        python --version
        python -V
        python3 -V
        python2 -V        
        pip install -r requirements.txt
        deactivate
        python --version
        python -V
        python3 -V
        python2 -V    
