name: "python2x virtualenv CI workflow ubuntu 20.04"


on:
  push:
    branches: [ test ]
  # pull_request:
  #   branches: [ githubactions_powershell ]


jobs:




  ubuntu-2004-python2x-job_0:
    name: "Setting Up Python 2x on ubuntu-20.04"
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status 
    - name: "Setting Up Python 2x virtual environment (source virtualenv)"
      run: |
        set -o errexit
        set -o pipefail
        set -o nounset
        set -o xtrace
        echo "=============Setting Up Python 2x Virtual Environment=="
        sudo apt-get update -qq
        python --version
        python -V
        python3 -V
        python2 -V 
        sudo pip install virtualenv
        virtualenv -p $(which python2) ~venvpy2
        source ~venvpy2/bin/activate
        python --version
        pip install -r requirements.txt         
        deactivate
        python --version
        python -V
        python3 -V
        python2 -V

  ubuntu-2004-python2x-job_1:
    name: "Setting Up Python 2x on ubuntu-20.04"
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status 
    - name: "Setting Up Python 2x virtual environment (.virtualenv)"
      run: |
        set -o errexit
        set -o pipefail
        set -o nounset
        set -o xtrace
        echo "=============Setting Up Python 2x Virtual Environment=="
        sudo apt-get update -qq
        python --version
        python -V
        python3 -V
        python2 -V 
        sudo pip install virtualenv
        virtualenv .virtualenv
        . .virtualenv/bin/activate
        python --version
        pip install -r requirements.txt         
        deactivate
        python --version
        python -V
        python3 -V
        python2 -V        